[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-generativeai>=0.3.0",
    "dotenv>=0.9.9",
    "mcp>=1.1.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
